language: node_js
node_js:
 - "8"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g gulp
  - npm install -g gulp-minify-html
  - npm install -g gulp-minify-css
  - npm install -g gulp-uglify
  - npm install -g gulp-concat
  - npm install -g gulp-imagemin
after_success:
  - gulp
  - firebase deploy --token $FIREBASE_TOKEN
