language: node_js
node_js:
 - "8"
branches:
  only:
   - master
install:
  - npm install -g firebase-tools
script:
  - npm install
  - gulp
  - staticrypt -f dist/password_template.html -t "Jared's Page" -i "Contact Jared" -o dist/protected.html src/protected.html jared
  - echo "Deploying!"
  - firebase deploy --token $FIREBASE_TOKEN
after_success:
  - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$ZONE/purge_cache" \ -H "X-Auth-Email: $AUTH_EMAIL" \ -H "X-Auth-Key: $AUTH_KEY" \ -H "Content-Type: application/json" \ --data '{"purge_everything":true}'
  - echo "Success"
