language: node_js
node_js:
 - "8"
install:
  - npm install -g firebase-tools
script:
  - npm install
  - gulp
  - echo "Deploying!"
  - firebase deploy --token $FIREBASE_TOKEN
after_success:
  - echo "Success"
