language: node_js
node_js:
 - "8"
branches:
  only:
   - master
install:
  - npm install -g firebase-tools
script:
  - npm install
  - gulp
  - staticrypt -f dist/password_template.html -t "Jared's Page" -i "Contact Jared" -o dist/protected.html src/protected.html jared
  - staticrypt -f dist/password_template.html -t "Seth's Page" -i "BB is a 67" -o dist/seth.html src/seth.html 67
  - staticrypt -f dist/password_template.html -t "Zack's Page" -i "What do you want?" -o dist/zack.html dist/seth.html Award

  - echo "Deploying!"
  - firebase deploy --token $FIREBASE_TOKEN
after_success:
  - bash clearcache.sh
  - echo "Success"
