language: node_js
node_js:
 - "8"
branches:
  only:
   - master
install:
  - npm install -g firebase-tools
script:
  - npm install
  - gulp
  - staticrypt -f dist/password_template.html -o dist/protected.html dist/protected.html jared
  - echo "Deploying!"
  - firebase deploy --token $FIREBASE_TOKEN
after_success:
  - echo "Success"
